services:
  postgres_test:
    image: postgres:15
    container_name: focusflow_postgres_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: usertest
      POSTGRES_PASSWORD: senhatest
      POSTGRES_DB: focusflow_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
